version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      day: monday
    ignore:
      - dependency-name: "@octokit/rest"
        # starting with v21, @octokit/rest is using ESM
        versions: ^21.0.0
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      day: monday
    groups:
      all:
        patterns:
          - "*"
